arb-dir: lib/l10n
template-arb-file: example_en.arb
output-localization-file: example_localizations.dart
output-class: ExampleLocalizations
output-dir: lib/l10n
synthetic-package: false
nullable-getter: false
